USE AJOVECO_NE

DROP FUNCTION X_CUENTASMAYORES;
DROP FUNCTION X_BALANCE_LOGICA_CC;
DROP FUNCTION X_BALANCE_CC;
DROP FUNCTION X_SALDO_CUENTANIIF_CC;

GO

-- SELECT * FROM X_BALANCE_CC('132074', 2023, 01) ORDER BY CODIGOCTA

GO

CREATE FUNCTION [dbo].[X_CUENTASMAYORES]
(
	@CODIGOCTA char(500)
)
RETURNS @cuentas TABLE (codigocta VARCHAR(255))
AS
BEGIN
	DECLARE @longitud int
    DECLARE @resultado char(500)

	SET @longitud = LEN(@codigocta) - 1
    SET @resultado = NULL

    WHILE @longitud > 0 AND @resultado IS NULL
    BEGIN
		INSERT INTO @cuentas SELECT CODIGOCTA FROM CUENTASNIF WHERE CODIGOCTA = LEFT(@codigocta, @longitud)
        SET @longitud = @longitud - 1
    END
	RETURN;
END;

GO 

-- FUNCIÓN QUE ENCAPSULA LA LÓGICA DEL BALANCE. NO DEBE SER CONSUMIDA.

CREATE FUNCTION [dbo].[X_BALANCE_LOGICA_CC]
(
	@codcc char(500),
	@ano numeric,
	@periodo numeric
)
RETURNS @balance TABLE 
(
	ID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	CODIGOCTA VARCHAR(255),
	CODCC VARCHAR(255),
	SALDO_ANTERIOR NUMERIC, 
	DEBITO NUMERIC, 
	CREDITO NUMERIC, 
	AUXILIAR NUMERIC
)
AS
BEGIN

INSERT INTO @balance 
	SELECT 
	CODIGOCTA, 
	@codcc CODCC,
	0 SALDO_ANTERIOR,
	SUM(DEBITO) DEBITO, 
	SUM(CREDITO) CREDITO,
	1 AUXILIAR
	FROM 
	MVTONIIF 
	WHERE 
	CODCC = @codcc AND
	YEAR (FECHAMVTO) = @ano AND 
	MONTH(FECHAMVTO) = @periodo
	GROUP BY 
	CODIGOCTA

	DECLARE @RowsToProcess  int
	DECLARE @CurrentRow     int
	DECLARE @cuentaBuscar   VARCHAR(255)

	SET @RowsToProcess = @@ROWCOUNT

	SET @CurrentRow=0
	WHILE @CurrentRow<@RowsToProcess
	BEGIN
		SET @CurrentRow = @CurrentRow + 1
		SELECT
			@cuentaBuscar = CODIGOCTA
			FROM @balance
			WHERE ID = @CurrentRow
		INSERT INTO @balance SELECT CODIGOCTA, @codcc, 0, 0, 0, 0 FROM X_CUENTASMAYORES(@cuentaBuscar)
	END;
RETURN
END;

GO

CREATE FUNCTION [dbo].[X_BALANCE_CC]
(
	@codcc char(500),
	@ano numeric,
	@periodo numeric
)
RETURNS TABLE
AS
RETURN 
(
	SELECT 
	BAL.CODIGOCTA,
	(SELECT SUM(DEBITO) FROM X_BALANCE_LOGICA_CC(@codcc, CASE WHEN @periodo = 1 THEN @ano - 1 ELSE @ano END, CASE WHEN @periodo = 1 THEN 12 ELSE @periodo - 1 END) WHERE CODIGOCTA LIKE RTRIM(BAL.CODIGOCTA) + '%') -
	(SELECT SUM(CREDITO) FROM X_BALANCE_LOGICA_CC(@codcc, CASE WHEN @periodo = 1 THEN @ano - 1 ELSE @ano END, CASE WHEN @periodo = 1 THEN 12 ELSE @periodo - 1 END) WHERE CODIGOCTA LIKE RTRIM(BAL.CODIGOCTA) + '%')
	SALDO_ANTERIOR,
	CASE 
	WHEN 
	BAL.AUXILIAR = 1 
	THEN 
	SUM(BAL.DEBITO) 
	ELSE 
	(SELECT SUM(DEBITO) FROM X_BALANCE_LOGICA_CC(@codcc, @ano, @periodo) WHERE CODIGOCTA LIKE RTRIM(BAL.CODIGOCTA) + '%') 
	END 
	DEBITO, 
	CASE 
	WHEN 
	BAL.AUXILIAR = 1 
	THEN 
	SUM(BAL.CREDITO) 
	ELSE
	(SELECT SUM(CREDITO) FROM X_BALANCE_LOGICA_CC(@codcc, @ano, @periodo) WHERE CODIGOCTA LIKE RTRIM(BAL.CODIGOCTA) + '%')
	END 
	CREDITO, 
	BAL.AUXILIAR
	FROM 
	X_BALANCE_LOGICA_CC(@codcc, @ano, @periodo) BAL
	GROUP BY CODIGOCTA, AUXILIAR
)