--SELECT * FROM X_BALANCE_CC('0132159', 2023, 01) ORDER BY CODIGOCTA


DROP FUNCTION X_CUENTASMAYORES;
DROP FUNCTION X_BALANCE_LOGICA_CC;
DROP FUNCTION X_BALANCE_CC;
DROP FUNCTION X_SALDOCUENTA_NIIF_CC;

GO
--SELECT * FROM SALDCONTNI 
--WHERE DATEFROMPARTS(ANO, CASE WHEN PERIODO = 13 THEN 12 ELSE PERIODO END, 1) < '20230101' and codcc = '0132159   '
-- SELECT * FROM X_BALANCE_CC('5', 2023, 01) ORDER BY CODIGOCTA

GO

CREATE FUNCTION [dbo].[X_CUENTASMAYORES]
(
	@CODIGOCTA varchar(20)
)
RETURNS @cuentas TABLE (codigocta varchar(20), nombrecta varchar(100))
AS
BEGIN
	DECLARE @longitud int
    DECLARE @resultado varchar(100)

	SET @longitud = LEN(@codigocta) - 1
    SET @resultado = NULL

    WHILE @longitud > 0 AND @resultado IS NULL
    BEGIN
		INSERT INTO @cuentas SELECT CODIGOCTA, DESCRIPCIO FROM CUENTASNIF WHERE CODIGOCTA = LEFT(@codigocta, @longitud)
        SET @longitud = @longitud - 1
    END
	RETURN;
END;

GO 

--SELECT * FROM X_BALANCE_LOGICA_CC('5232092', 2023, 01) ORDER BY CODIGOCTA
--SELECT * FROM X_BALANCE_CC('5', 2022, 01) ORDER BY CODIGOCTA
--SELECT DEBITO - CREDITO FROM SALDCONTNI WHERE CODCC =  AND CODIGOCTA =  AND PERIODO = 11 AND ANO = 2022
--SELECT dbo.X_SALDOCUENTA_NIIF_CC('20230101', '11050501', '5232092')
--SELECT * FROM SALDCONTNI WHERE CODIGOCTA = '11050501' AND CODCC = '5232092'

CREATE FUNCTION [dbo].[X_SALDOCUENTA_NIIF_CC]
(
@fecha date,
@cuenta varchar(20),
@codcc varchar(20)
)
RETURNS NUMERIC(17,2)
AS
	BEGIN
	DECLARE @valor NUMERIC(17,2)
	SELECT @valor = (
	SELECT ISNULL(SUM (TEMP.DEBITO) - SUM(TEMP.CREDITO), 0) SALDO_INICIAL FROM
	(
		SELECT
		DATEFROMPARTS(CAST(ANO AS INT),
		CASE WHEN PERIODO = 13 THEN 12 ELSE CAST (PERIODO AS INT) END, 1) FECHA, *
		FROM SALDCONTNI) TEMP
		WHERE TEMP.CODIGOCTA LIKE RTRIM(@cuenta) + '%' AND TEMP.CODCC = @codcc AND TEMP.FECHA < @fecha
	)
	RETURN @valor
END

GO

CREATE FUNCTION [dbo].[X_BALANCE_LOGICA_CC]
(
	@codcc varchar(20),
	@ano numeric,
	@periodo numeric
)
RETURNS @balance TABLE 
(
	ID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	CODIGOCTA varchar(20),
	NOMBRECTA varchar(100),
	CODCC varchar(20),
	SALDO_INICIAL NUMERIC, 
	DEBITO NUMERIC, 
	CREDITO NUMERIC, 
	AUXILIAR NUMERIC
)
AS
BEGIN

INSERT INTO @balance 
	SELECT 
	SALDCONTNI.CODIGOCTA, 
	CUENTASNIF.DESCRIPCIO,
	SALDCONTNI.CODCC,
	dbo.X_SALDOCUENTA_NIIF_CC(DATEFROMPARTS(CAST(@ano AS INT), CAST(@periodo AS INT), 1), SALDCONTNI.CODIGOCTA, CODCC) SALDO_INICIAL,
	CASE WHEN ANO = @ano AND PERIODO = @periodo THEN SUM(DEBITO) ELSE 0 END DEBITO, 
	CASE WHEN ANO = @ano AND PERIODO = @periodo THEN SUM(CREDITO) ELSE 0 END CREDITO,
	1 AUXILIAR
	FROM 
	SALDCONTNI,
	CUENTASNIF
	WHERE 
	CODCC LIKE RTRIM(@codcc) + '%' AND
	DATEFROMPARTS(ANO, CASE WHEN PERIODO = 13 THEN 12 ELSE PERIODO END, 1) <= DATEFROMPARTS(@ano, @periodo, 1) AND
	CUENTASNIF.CODIGOCTA = SALDCONTNI.CODIGOCTA
	GROUP BY 
	SALDCONTNI.CODIGOCTA, SALDCONTNI.CODCC, CUENTASNIF.DESCRIPCIO, SALDCONTNI.ANO, SALDCONTNI.PERIODO

	DECLARE @RowsToProcess  int
	DECLARE @CurrentRow     int
	DECLARE @cuentaBuscar   varchar(20)

	SET @RowsToProcess = @@ROWCOUNT

	SET @CurrentRow=0
	WHILE @CurrentRow<@RowsToProcess
	BEGIN
		SET @CurrentRow = @CurrentRow + 1
		SELECT
			@cuentaBuscar = CODIGOCTA
			FROM @balance
			WHERE ID = @CurrentRow
		INSERT INTO @balance SELECT CODIGOCTA, NOMBRECTA, @codcc, dbo.X_SALDOCUENTA_NIIF_CC(DATEFROMPARTS(CAST(@ano AS INT), CAST(@periodo AS INT), 1), CODIGOCTA, @codcc) SALDO_INICIAL, 0, 0, 0 FROM X_CUENTASMAYORES(@cuentaBuscar)
	END;
RETURN
END;

GO

CREATE FUNCTION [dbo].[X_BALANCE_CC]
(
	@codcc varchar(20),
	@ano numeric,
	@periodo numeric
)
RETURNS TABLE
AS
RETURN 
(
	SELECT 
	BAL.CODIGOCTA,
	BAL.CODCC,
	BAL.NOMBRECTA,
	BAL.SALDO_INICIAL,	
	CASE 
	WHEN 
	BAL.AUXILIAR = 1 
	THEN 
	SUM(BAL.DEBITO) 
	ELSE 
	(SELECT SUM(DEBITO) FROM X_BALANCE_LOGICA_CC(@codcc, @ano, @periodo) WHERE CODIGOCTA LIKE RTRIM(BAL.CODIGOCTA) + '%') 
	END 
	DEBITO, 
	CASE 
	WHEN 
	BAL.AUXILIAR = 1 
	THEN 
	SUM(BAL.CREDITO) 
	ELSE
	(SELECT SUM(CREDITO) FROM X_BALANCE_LOGICA_CC(@codcc, @ano, @periodo) WHERE CODIGOCTA LIKE RTRIM(BAL.CODIGOCTA) + '%')
	END 
	CREDITO,
	BAL.AUXILIAR
	FROM 
	X_BALANCE_LOGICA_CC(@codcc, @ano, @periodo) BAL
	GROUP BY CODIGOCTA, NOMBRECTA, CODCC, AUXILIAR, SALDO_INICIAL
)
